<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="108245" started-at="2014-08-05T19:42:02Z" finished-at="2014-08-05T19:43:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="108245" started-at="2014-08-05T19:42:02Z" finished-at="2014-08-05T19:43:50Z">
      <class name="persistent.wordpressautomation.PageObject_TC">
        <test-method status="FAIL" signature="TestCase1()[pri:0, instance:persistent.wordpressautomation.PageObject_TC@2d10dd87]" name="TestCase1" duration-ms="92658" started-at="2014-08-06T01:12:02Z" finished-at="2014-08-06T01:13:34Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.InstantiationException: persistent.wordpressautomation.PageObjects.Post]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.InstantiationException: persistent.wordpressautomation.PageObjects.Post
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:136)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:66)
	at persistent.wordpressautomation.PageObjects.Dashboard.click_New_Post(Dashboard.java:53)
	at persistent.wordpressautomation.PageObject_TC.TestCase1(PageObject_TC.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.InstantiationException: persistent.wordpressautomation.PageObjects.Post
	at java.lang.Class.newInstance0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:133)
	... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
      </class> <!-- persistent.wordpressautomation.PageObject_TC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
